// ============================================================
//  LegalNews.js — Advocates Hub Legal News & Supreme Court Updates
//  Part of the 4 Legal Sections:
//    1. Ask a Question  2. Legal Documents  3. Bare Acts  4. Legal News
//  Supports White & Dark Themes with English & Kannada translations
// ============================================================

import React, { useState, useMemo, useEffect } from "react";
import { getTheme } from "../data/themeStore";
import "./LegalNews.css";

export const NEWS_CATEGORIES_EN = [
  "All", "Supreme Court", "High Courts", "Corporate Law", "Criminal Law", "New Legislation"
];

export const NEWS_CATEGORIES_KN = [
  "ಎಲ್ಲಾ", "ಸುಪ್ರೀಂ ಕೋರ್ಟ್", "ಹೈಕೋರ್ಟ್‌ಗಳು", "ಕಾರ್ಪೊರೇಟ್ ಕಾನೂನು", "ಕ್ರಿಮಿನಲ್ ಕಾನೂನು", "ಹೊಸ ಶಾಸನಗಳು"
];

export const NEWS_CATEGORIES = NEWS_CATEGORIES_EN;

export const LEGAL_NEWS_DATA = [
  {
    id: 1,
    title: "Maternity Leave Cannot Cost Women Their Careers: Delhi High Court Orders ₹10 Lakh Compensation",
    titleKn: "ಪ್ರಸೂತಿ ರಜೆ ಮಹಿಳೆಯರ ವೃತ್ತಿಜೀವನಕ್ಕೆ ಅಡ್ಡಿಯಾಗಬಾರದು: ದೆಹಲಿ ಹೈಕೋರ್ಟ್ ಆದೇಶ",
    category: "High Courts",
    date: "September 2, 2026",
    author: "Advocates Hub Legal Desk",
    readTime: "4 min read",
    summary: "Delhi High Court rules that Section 12 of the Maternity Benefit Act protects women from disadvantageous changes in service conditions or demotions post maternity leave.",
    summaryKn: "ಪ್ರಸೂತಿ ರಜೆಯ ನಂತರ ಮಹಿಳೆಯರ ಹುದ್ದೆ ಅಥವಾ ವೇತನದಲ್ಲಿ ಯಾವುದೇ ವ್ಯತ್ಯಾಸ ಮಾಡದಂತೆ ದೆಹಲಿ ಹೈಕೋರ್ಟ್ ಮಹತ್ವದ ಆದೇಶ ನೀಡಿದೆ.",
    content: `The Delhi High Court has held that a woman returning from maternity leave is ordinarily entitled to be restored to the same position she held before going on leave and cannot be placed at a professional disadvantage because of pregnancy or motherhood. 

    Justice Sachin Datta emphasized that Section 12 of the Maternity Benefit Act, 1961 does not merely protect a woman from dismissal during maternity leave, but also shields her from any disadvantageous change in service conditions. 
    
    The court ordered the employer to pay ₹10 lakh as compensation and ₹1.5 lakh towards costs, noting that maternity protection is rooted in constitutional guarantees of equality, dignity, and reproductive autonomy.`,
    isBreaking: true
  },
  {
    id: 2,
    title: "Supreme Court Sets Aside ₹425-Crore Penalty as Customs Authority Used AI-Generated Fake Case Laws",
    titleKn: "ಕೃತಕ ಬುದ್ಧಿಮತ್ತೆ (AI) ಸೃಷ್ಟಿಸಿದ ನಕಲಿ ತೀರ್ಪುಗಳ ಬಳಕೆ: ₹೪೨೫ ಕೋಟಿ ದಂಡ ರದ್ದುಪಡಿಸಿದ ಸುಪ್ರೀಂ ಕೋರ್ಟ್",
    category: "Supreme Court",
    date: "September 2, 2026",
    author: "Supreme Court Bureau",
    readTime: "5 min read",
    summary: "In a strict warning regarding artificial intelligence reliance, the Apex Court quashed a customs penalty order after discovering fabricated citations generated by AI tools.",
    summaryKn: "ನ್ಯಾಯಾಂಗ ವಿಚಾರಣೆಯಲ್ಲಿ ನಕಲಿ ತೀರ್ಪುಗಳ ಆಧಾರದ ಮೇಲೆ ನೀಡಲಾಗಿದ್ದ ಬೃಹತ್ ದಂಡದ ಆದೇಶವನ್ನು ಸುಪ್ರೀಂ ಕೋರ್ಟ್ ರದ್ದುಗೊಳಿಸಿದೆ.",
    content: `The Supreme Court of India set aside a massive ₹425-crore customs penalty order after it came to light that the authorities used AI-generated fictitious case laws and judgments in their adjudication process. 

    Expressing deep concern, the bench remarked that entrusting unverified automated tools with judicial or quasi-judicial assessment parameters creates hazardous precedents. The court mandated strict verification guidelines for all state and statutory bodies referencing digital or AI-assisted case precedents.`,
    isBreaking: true
  },
  {
    id: 3,
    title: "Banks Can Invoke SARFAESI Act for Financial Assets Acquired From NBFCs",
    titleKn: "NBFC ಗಳಿಂದ ಪಡೆದ ಸಾಲ ವಸೂಲಾತಿಗೂ SARFAESI ಕಾಯ್ದೆ ಅನ್ವಯ: ಸುಪ್ರೀಂ ಕೋರ್ಟ್ ಸ್ಪಷ್ಟನೆ",
    category: "Supreme Court",
    date: "September 1, 2026",
    author: "Banking Law Division",
    readTime: "3 min read",
    summary: "Supreme Court clarifies the legal scope enabling scheduled banks to initiate recovery proceedings under SARFAESI for loans originally extended by non-banking financial companies.",
    summaryKn: "ಬ್ಯಾಂಕ್‌ಗಳು ಎನ್‌ಬಿಎಫ್‌ಸಿಗಳಿಂದ ಪಡೆದುಕೊಂಡ ಸಾಲದ ಆಸ್ತಿಗಳ ಮೇಲೆ ನೇರ ಕ್ರಮ ಕೈಗೊಳ್ಳಲು ಸುಪ್ರೀಂ ಕೋರ್ಟ್ ಅನುಮತಿ ನೀಡಿದೆ.",
    content: `In a major boost to asset reconstruction and banking liquidity, the Supreme Court ruled that banks possess the authority to invoke the SARFAESI Act for financial assets and loans acquired from NBFCs, even if the specific entity was originally outside certain traditional coverage boundaries. 

    The ruling streamlines asset transfer mechanisms and strengthens mechanisms for dealing with non-performing assets (NPAs) across the Indian financial sector.`,
    isBreaking: false
  },
  {
    id: 4,
    title: "Implementation Challenges of BNS, BNSS, and BSA: One Year Review by Legal Experts",
    titleKn: "ಹೊಸ ಅಪರಾಧ ಸಂಹಿತೆಗಳ ಒಂದು ವರ್ಷದ ಅವಲೋಕನ: ತನಿಖಾ ಸಂಸ್ಥೆಗಳ ಡಿಜಿಟಲೀಕರಣ ಪ್ರಗತಿ",
    category: "New Legislation",
    date: "August 28, 2026",
    author: "Senior Editorial Panel",
    readTime: "6 min read",
    summary: "An analysis of how lawyers, investigators, and trial courts across India are adapting to the newly instated criminal framework replacing the IPC, CrPC, and Evidence Act.",
    summaryKn: "IPC, CrPC ಬದಲಿಗೆ ಜಾರಿಗೆ ಬಂದಿರುವ BNS ಮತ್ತು BNSS ಕಾಯ್ದೆಗಳ ಜಾರಿಯಲ್ಲಿನ ಸಾಧಕ ಬಾಧಕಗಳ ಪರಿಶೀಲನೆ.",
    content: `A year after the comprehensive overhaul of India's criminal jurisprudence through the Bharatiya Nyaya Sanhita (BNS), Bharatiya Nagarik Suraksha Sanhita (BNSS), and Bharatiya Sakshya Adhiniyam (BSA), legal practitioners share mixed reviews. 

    While digital integration and electronic evidence protocols have accelerated filing transparency, training rural investigation units and matching judicial infrastructure remain primary hurdles for smooth implementation.`,
    isBreaking: false
  },
  {
    id: 5,
    title: "Bombay High Court Upholds Land Acquisition for Dr. B.R. Ambedkar Mural Construction",
    titleKn: "ಡಾ. ಬಿ.ಆರ್. ಅಂಬೇಡ್ಕರ್ ಸ್ಮಾರಕ ನಿರ್ಮಾಣಕ್ಕಾಗಿ ಭೂಸ್ವಾಧೀನ ಎತ್ತಿಹಿಡಿದ ಬಾಂಬೆ ಹೈಕೋರ್ಟ್",
    category: "High Courts",
    date: "August 27, 2026",
    author: "Regional Bureau",
    readTime: "3 min read",
    summary: "Court rules that acquisition of land for public memorials serving educational and inspirational community goals firmly constitutes a valid 'public purpose'.",
    summaryKn: "ಸಾರ್ವಜನಿಕ ಪ್ರೇರಣಾ ಸ್ಥಳಗಳ ನಿರ್ಮಾಣವು ಕಾನೂನುಬದ್ಧ 'ಸಾರ್ವಜನಿಕ ಉದ್ದೇಶ'ದ ವ್ಯಾಪ್ತಿಗೆ ಬರುತ್ತದೆ ಎಂದು ಕೋರ್ಟ್ ತೀರ್ಪು ನೀಡಿದೆ.",
    content: `The Bombay High Court formally upheld land acquisition proceedings executed for constructing a monumental mural dedicated to Dr. B.R. Ambedkar, dismissing challenges raised over alternative land usage. 

    The division bench noted that honoring figures of national importance and fostering public civic education qualifies securely under legally defensible public purposes.`,
    isBreaking: false
  },
  {
    id: 6,
    title: "Corporate Governance Update: Ministry Revises Independent Director Compliance Norms",
    titleKn: "ಕಾರ್ಪೊರೇಟ್ ಆಡಳಿತ: ಸ್ವತಂತ್ರ ನಿರ್ದೇಶಕರ ಮಾರ್ಗಸೂಚಿಗಳನ್ನು ಪರಿಷ್ಕರಿಸಿದ ಕಾರ್ಪೊರೇಟ್ ವ್ಯವಹಾರಗಳ ಸಚಿವಾಲಯ",
    category: "Corporate Law",
    date: "August 25, 2026",
    author: "Corporate Compliance Desk",
    readTime: "4 min read",
    summary: "New MCA guidelines streamline performance evaluation frameworks and disclosure requirements for independent directors across listed business entities.",
    summaryKn: "ಕಂಪನಿಗಳ ಮಂಡಳಿಯಲ್ಲಿ ಪಾರದರ್ಶಕತೆ ಹೆಚ್ಚಿಸಲು ಹೊಸ ಡಿಜಿಟಲ್ ರಿಪೋರ್ಟಿಂಗ್ ನಿಯಮಗಳನ್ನು ಜಾರಿಗೆ ತರಲಾಗಿದೆ.",
    content: `The Ministry of Corporate Affairs (MCA) has issued updated clarifications regarding the operational responsibilities and digital reporting disclosures required from independent directors. 

    The framework aims to reduce compliance friction while strengthening audit committee oversights and accountability metrics in corporate boards.`,
    isBreaking: false
  }
];

export default function LegalNews() {
  const [theme, setTheme] = useState(getTheme);

  useEffect(() => {
    const handleTheme = (e) => setTheme(e?.detail || getTheme());
    window.addEventListener("law4u_theme_change", handleTheme);
    return () => window.removeEventListener("law4u_theme_change", handleTheme);
  }, []);

  const [lang, setLang] = useState(() => {
    try {
      return localStorage.getItem("law4u_home_lang") || "en";
    } catch {
      return "en";
    }
  });

  useEffect(() => {
    const handleLang = (e) => {
      if (e?.detail) setLang(e.detail);
      else {
        try {
          setLang(localStorage.getItem("law4u_home_lang") || "en");
        } catch {}
      }
    };
    window.addEventListener("law4u_lang_change", handleLang);
    return () => window.removeEventListener("law4u_lang_change", handleLang);
  }, []);

  const isKn = lang === "kn";

  const [selectedCategory, setSelectedCategory] = useState("All");
  const [searchQuery, setSearchQuery] = useState("");
  const [activeArticle, setActiveArticle] = useState(null);
  const [copyToast, setCopyToast] = useState(false);

  // Filter and search logic
  const filteredNews = useMemo(() => {
    return LEGAL_NEWS_DATA.filter((item) => {
      const matchesCategory = selectedCategory === "All" || item.category === selectedCategory;
      const q = searchQuery.toLowerCase().trim();
      const matchesSearch =
        !q ||
        item.title.toLowerCase().includes(q) ||
        (item.titleKn && item.titleKn.toLowerCase().includes(q)) ||
        item.summary.toLowerCase().includes(q) ||
        item.category.toLowerCase().includes(q);
      return matchesCategory && matchesSearch;
    });
  }, [selectedCategory, searchQuery]);

  const handleShare = (article) => {
    const shareText = `${article.title} — via Advocates Hub\n${window.location.href}`;
    if (navigator.clipboard) {
      navigator.clipboard.writeText(shareText).then(() => {
        setCopyToast(true);
        setTimeout(() => setCopyToast(false), 2600);
      }).catch(() => {});
    }
  };

  const breakingArticle = LEGAL_NEWS_DATA.find((item) => item.isBreaking) || LEGAL_NEWS_DATA[0];

  return (
    <div className={`ln-page ${theme === "dark" ? "ln-dark" : "ln-light"}`}>
      {/* Header */}
      <header className="ln-header">
        <div className="ln-header-content">
          <span className="ln-badge-top">
            {isKn ? "📰 ನ್ಯಾಯಾಂಗ ಮತ್ತು ಸುಪ್ರೀಂ ಕೋರ್ಟ್ ಅಪ್ಡೇಟ್ಸ್" : "📰 Judicial Verdicts & Supreme Court Updates"}
          </span>
          <h1 className="ln-title">
            {isKn ? "ಭಾರತೀಯ ಕಾನೂನು & ನ್ಯಾಯಾಲಯ ಸುದ್ದಿಗಳು" : "India Legal News & Court Judgments"}
          </h1>
          <p className="ln-subtitle">
            {isKn
              ? "ಸುಪ್ರೀಂ ಕೋರ್ಟ್, ಹೈಕೋರ್ಟ್ ತೀರ್ಪುಗಳು ಮತ್ತು ಹೊಸ ಶಾಸನಗಳ ವಿಶ್ವಾಸಾರ್ಹ ಕಾನೂನು ವಿಶ್ಲೇಷಣೆ."
              : "Timely judicial reporting, constitutional analyses, and landmark rulings directly from the Apex Court and High Courts."}
          </p>
        </div>
      </header>

      {/* Breaking News Ticker */}
      {breakingArticle && (
        <aside className="ln-ticker-container" aria-label="Breaking legal alert">
          <span className="ln-ticker-label">⚡ {isKn ? "ತಾಜಾ ಸುದ್ದಿ" : "BREAKING"}</span>
          <span
            className="ln-ticker-text"
            onClick={() => setActiveArticle(breakingArticle)}
            role="button"
            tabIndex={0}
            onKeyDown={(e) => {
              if (e.key === "Enter") setActiveArticle(breakingArticle);
            }}
          >
            {isKn && breakingArticle.titleKn ? breakingArticle.titleKn : breakingArticle.title}
            <small> · {breakingArticle.readTime}</small>
          </span>
        </aside>
      )}

      {/* Main Container */}
      <main className="ln-container">
        {/* Controls Bar (Search + Categories) */}
        <section className="ln-controls-bar">
          <div className="ln-search-wrapper">
            <span className="ln-search-icon">🔍</span>
            <input
              type="text"
              className="ln-search-input"
              placeholder={
                isKn
                  ? "ಸುದ್ದಿ, ಕೋರ್ಟ್ ಹೆಸರು, ಅಥವಾ ಕೀವರ್ಡ್ ಮೂಲಕ ಹುಡುಕಿ..."
                  : "Search judgements, courts, or legal topics..."
              }
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
            {searchQuery && (
              <button
                type="button"
                className="ln-search-clear"
                onClick={() => setSearchQuery("")}
                aria-label="Clear search"
              >
                ✕
              </button>
            )}
          </div>

          <div className="ln-categories-scroll">
            {NEWS_CATEGORIES_EN.map((cat, idx) => {
              const label = isKn ? NEWS_CATEGORIES_KN[idx] || cat : cat;
              return (
                <button
                  key={cat}
                  type="button"
                  className={`ln-cat-btn ${selectedCategory === cat ? "active" : ""}`}
                  onClick={() => setSelectedCategory(cat)}
                >
                  {label}
                </button>
              );
            })}
          </div>
        </section>

        {/* Results Metadata */}
        <div className="ln-meta-results">
          {isKn ? (
            <>
              <strong>{filteredNews.length}</strong> ಕಾನೂನು ವರದಿಗಳು ಲಭ್ಯವಿವೆ
            </>
          ) : (
            <>
              Showing <strong>{filteredNews.length}</strong> judicial reports & rulings
            </>
          )}
        </div>

        {/* News Grid */}
        <section className="ln-grid">
          {filteredNews.map((article) => (
            <article key={article.id} className="ln-card">
              <div className="ln-card-header">
                <span className="ln-card-cat">{article.category}</span>
                <span className="ln-card-read">{article.readTime}</span>
              </div>

              <h2 className="ln-card-title">
                {isKn && article.titleKn ? article.titleKn : article.title}
              </h2>

              <p className="ln-card-summary">
                {isKn && article.summaryKn ? article.summaryKn : article.summary}
              </p>

              <div className="ln-card-footer">
                <span className="ln-card-date">📅 {article.date}</span>
                <button
                  type="button"
                  className="ln-card-btn"
                  onClick={() => setActiveArticle(article)}
                >
                  {isKn ? "ಪೂರ್ಣ ಸುದ್ದಿ ಓದಿ →" : "Read Full Story →"}
                </button>
              </div>
            </article>
          ))}
        </section>

        {filteredNews.length === 0 && (
          <div className="ln-empty-state">
            <span className="ln-empty-icon">⚖️</span>
            <h3>{isKn ? "ಯಾವುದೇ ಸುದ್ದಿ ಕಂಡುಬಂದಿಲ್ಲ" : "No Judicial Reports Found"}</h3>
            <p>
              {isKn
                ? "ದಯವಿಟ್ಟು ಬೇರೆ ಕೀವರ್ಡ್ ಹುಡುಕಾಟ ಅಥವಾ 'ಎಲ್ಲಾ' ವರ್ಗವನ್ನು ಪ್ರಯತ್ನಿಸಿ."
                : "Try searching with broader legal keywords or select 'All' categories."}
            </p>
          </div>
        )}
      </main>

      {/* Article Detail Modal */}
      {activeArticle && (
        <div
          className="ln-modal-backdrop"
          onClick={(e) => {
            if (e.target === e.currentTarget) setActiveArticle(null);
          }}
        >
          <div className="ln-modal-box">
            <div className="ln-modal-top">
              <span className="ln-card-cat">{activeArticle.category}</span>
              <button
                type="button"
                className="ln-modal-close-btn"
                onClick={() => setActiveArticle(null)}
                aria-label="Close article"
              >
                ✕
              </button>
            </div>

            <h2 className="ln-modal-title">
              {isKn && activeArticle.titleKn ? activeArticle.titleKn : activeArticle.title}
            </h2>

            <div className="ln-modal-meta">
              <span>✍️ {activeArticle.author}</span>
              <span>•</span>
              <span>📅 {activeArticle.date}</span>
              <span>•</span>
              <span>⏳ {activeArticle.readTime}</span>
            </div>

            <hr className="ln-divider" />

            <div className="ln-modal-body">
              {activeArticle.content.split("\n\n").map((para, i) => (
                <p key={i}>{para.trim()}</p>
              ))}
            </div>

            <div className="ln-modal-footer">
              <button
                type="button"
                className="ln-share-btn"
                onClick={() => handleShare(activeArticle)}
              >
                {copyToast ? (isKn ? "✓ ಲಿಂಕ್ ನಕಲಿಸಲಾಗಿದೆ" : "✓ Link Copied!") : (isKn ? "🔗 ಹಂಚಿಕೊಳ್ಳಿ" : "🔗 Share Story")}
              </button>
              <button
                type="button"
                className="ln-done-btn"
                onClick={() => setActiveArticle(null)}
              >
                {isKn ? "ಮುಕ್ತಾಯ" : "Close Article"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}