// LegalNews.js — Advocates Hub Legal News & Supreme Court Updates
import React, { useState, useMemo } from "react";
import "./LegalNews.css";

const NEWS_CATEGORIES = [
  "All", "Supreme Court", "High Courts", "Corporate Law", "Criminal Law", "New Legislation"
];

const LEGAL_NEWS_DATA = [
  {
    id: 1,
    title: "Maternity Leave Cannot Cost Women Their Careers: Delhi High Court Orders ₹10 Lakh Compensation",
    category: "High Courts",
    date: "September 2, 2026",
    author: "Advocates Hub Legal Desk",
    readTime: "4 min read",
    summary: "Delhi High Court rules that Section 12 of the Maternity Benefit Act protects women from disadvantageous changes in service conditions or demotions post maternity leave.",
    content: `The Delhi High Court has held that a woman returning from maternity leave is ordinarily entitled to be restored to the same position she held before going on leave and cannot be placed at a professional disadvantage because of pregnancy or motherhood. 

    Justice Sachin Datta emphasized that Section 12 of the Maternity Benefit Act, 1961 does not merely protect a woman from dismissal during maternity leave, but also shields her from any disadvantageous change in service conditions. 
    
    The court ordered the employer to pay ₹10 lakh as compensation and ₹1.5 lakh towards costs, noting that maternity protection is rooted in constitutional guarantees of equality, dignity, and reproductive autonomy.`,
    isBreaking: true
  },
  {
    id: 2,
    title: "Supreme Court Sets Aside ₹425-Crore Penalty as Customs Authority Used AI-Generated Fake Case Laws",
    category: "Supreme Court",
    date: "September 2, 2026",
    author: "Supreme Court Bureau",
    readTime: "5 min read",
    summary: "In a strict warning regarding artificial intelligence reliance, the Apex Court quashed a customs penalty order after discovering fabricated citations generated by AI tools.",
    content: `The Supreme Court of India set aside a massive ₹425-crore customs penalty order after it came to light that the authorities used AI-generated fictitious case laws and judgments in their adjudication process. 

    Expressing deep concern, the bench remarked that entrusting unverified automated tools with judicial or quasi-judicial assessment parameters creates hazardous precedents. The court mandated strict verification guidelines for all state and statutory bodies referencing digital or AI-assisted case precedents.`,
    isBreaking: true
  },
  {
    id: 3,
    title: "Banks Can Invoke SARFAESI Act for Financial Assets Acquired From NBFCs",
    category: "Supreme Court",
    date: "September 1, 2026",
    author: "Banking Law Division",
    readTime: "3 min read",
    summary: "Supreme Court clarifies the legal scope enabling scheduled banks to initiate recovery proceedings under SARFAESI for loans originally extended by non-banking financial companies.",
    content: `In a major boost to asset reconstruction and banking liquidity, the Supreme Court ruled that banks possess the authority to invoke the SARFAESI Act for financial assets and loans acquired from NBFCs, even if the specific entity was originally outside certain traditional coverage boundaries. 

    The ruling streamlines asset transfer mechanisms and strengthens mechanisms for dealing with non-performing assets (NPAs) across the Indian financial sector.`,
    isBreaking: false
  },
  {
    id: 4,
    title: "Implementation Challenges of BNS, BNSS, and BSA: One Year Review by Legal Experts",
    category: "New Legislation",
    date: "August 28, 2026",
    author: "Senior Editorial Panel",
    readTime: "6 min read",
    summary: "An analysis of how lawyers, investigators, and trial courts across India are adapting to the newly instated criminal framework replacing the IPC, CrPC, and Evidence Act.",
    content: `A year after the comprehensive overhaul of India's criminal jurisprudence through the Bharatiya Nyaya Sanhita (BNS), Bharatiya Nagarik Suraksha Sanhita (BNSS), and Bharatiya Sakshya Adhiniyam (BSA), legal practitioners share mixed reviews. 

    While digital integration and electronic evidence protocols have accelerated filing transparency, training rural investigation units and matching judicial infrastructure remain primary hurdles for smooth implementation.`,
    isBreaking: false
  },
  {
    id: 5,
    title: "Bombay High Court Upholds Land Acquisition for Dr. B.R. Ambedkar Mural Construction",
    category: "High Courts",
    date: "August 27, 2026",
    author: "Regional Bureau",
    readTime: "3 min read",
    summary: "Court rules that acquisition of land for public memorials serving educational and inspirational community goals firmly constitutes a valid 'public purpose'.",
    content: `The Bombay High Court formally upheld land acquisition proceedings executed for constructing a monumental mural dedicated to Dr. B.R. Ambedkar, dismissing challenges raised over alternative land usage. 

    The division bench noted that honoring figures of national importance and fostering public civic education qualifies securely under legally defensible public purposes.`,
    isBreaking: false
  },
  {
    id: 6,
    title: "Corporate Governance Update: Ministry Revises Independent Director Compliance Norms",
    category: "Corporate Law",
    date: "August 25, 2026",
    author: "Corporate Compliance Desk",
    readTime: "4 min read",
    summary: "New MCA guidelines streamline performance evaluation frameworks and disclosure requirements for independent directors across listed business entities.",
    content: `The Ministry of Corporate Affairs (MCA) has issued updated clarifications regarding the operational responsibilities and digital reporting disclosures required from independent directors. 

    The framework aims to reduce compliance friction while strengthening audit committee oversights and accountability metrics in corporate boards.`,
    isBreaking: false
  }
];

export default function LegalNews() {
  const [selectedCategory, setSelectedCategory] = useState("All");
  const [searchQuery, setSearchQuery] = useState("");
  const [activeArticle, setActiveArticle] = useState(null);

  // Filter and search logic
  const filteredNews = useMemo(() => {
    return LEGAL_NEWS_DATA.filter((item) => {
      const matchesCategory = selectedCategory === "All" || item.category === selectedCategory;
      const matchesSearch = 
        item.title.toLowerCase().includes(searchQuery.toLowerCase()) || 
        item.summary.toLowerCase().includes(searchQuery.toLowerCase());
      return matchesCategory && matchesSearch;
    });
  }, [selectedCategory, searchQuery]);

  const breakingNews = LEGAL_NEWS_DATA.filter(item => item.isBreaking);

  return (
    <div className="ln-page">
      {/* Header Banner */}
      <div className="ln-header">
        <div className="ln-header-content">
          <span className="ln-badge-top">📰 Advocates Hub Chronicle</span>
          <h1 className="ln-title">Legal News & Court Updates</h1>
          <p className="ln-subtitle">
            Real-time coverage of Supreme Court judgments, High Court rulings, legislative shifts, and corporate law updates.
          </p>
        </div>
      </div>

      {/* Breaking News Ticker */}
      {breakingNews.length > 0 && (
        <div className="ln-ticker-container">
          <div className="ln-ticker-label">🔥 Breaking Updates</div>
          <div className="ln-ticker-content">
            <span className="ln-ticker-text" onClick={() => setActiveArticle(breakingNews[0])}>
              {breakingNews[0].title} — <small>Click to read full coverage</small>
            </span>
          </div>
        </div>
      )}

      {/* Main Content Area */}
      <div className="ln-container">
        {/* Search & Filters */}
        <div className="ln-controls-bar">
          <div className="ln-search-box">
            <span>🔍</span>
            <input 
              type="text" 
              placeholder="Search legal headlines, rulings, acts..." 
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
            {searchQuery && <button onClick={() => setSearchQuery("")}>✕</button>}
          </div>

          <div className="ln-categories">
            {NEWS_CATEGORIES.map((cat) => (
              <button 
                key={cat}
                className={`ln-cat-btn ${selectedCategory === cat ? "active" : ""}`}
                onClick={() => setSelectedCategory(cat)}
              >
                {cat}
              </button>
            ))}
          </div>
        </div>

        {/* News Grid */}
        {filteredNews.length === 0 ? (
          <div className="ln-no-results">
            <div style={{ fontSize: "40px" }}>📭</div>
            <h3>No legal articles found</h3>
            <p>Try modifying your keywords or switching categories.</p>
          </div>
        ) : (
          <div className="ln-grid">
            {filteredNews.map((news) => (
              <div key={news.id} className="ln-card" onClick={() => setActiveArticle(news)}>
                <div className="ln-card-header">
                  <span className="ln-card-cat">{news.category}</span>
                  <span className="ln-card-date">📅 {news.date}</span>
                </div>
                <h3 className="ln-card-title">{news.title}</h3>
                <p className="ln-card-summary">{news.summary}</p>
                <div className="ln-card-footer">
                  <span className="ln-card-author">✍️ {news.author}</span>
                  <span className="ln-card-read">Read Article →</span>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Article Reader Modal */}
      {activeArticle && (
        <div className="ln-modal-backdrop" onClick={() => setActiveArticle(null)}>
          <div className="ln-modal-box" onClick={(e) => e.stopPropagation()}>
            <div className="ln-modal-top">
              <span className="ln-modal-cat">{activeArticle.category}</span>
              <button className="ln-close-btn" onClick={() => setActiveArticle(null)}>✕</button>
            </div>
            <h2 className="ln-modal-title">{activeArticle.title}</h2>
            <div className="ln-modal-meta">
              <span>📅 {activeArticle.date}</span>
              <span>⏱️ {activeArticle.readTime}</span>
              <span>✍️ {activeArticle.author}</span>
            </div>
            <hr className="ln-divider" />
            <div className="ln-modal-body">
              {activeArticle.content.split("\n\n").map((par, index) => (
                <p key={index}>{par}</p>
              ))}
            </div>
            <div className="ln-modal-footer">
              <button className="ln-share-btn" onClick={() => alert("Article link copied to clipboard!")}>
                🔗 Share Legal Update
              </button>
              <button className="ln-done-btn" onClick={() => setActiveArticle(null)}>
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}